### ISSUE TITLE
epoll

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#550]
Module [epoll](https://modules.perl6.org/dist/epoll) cannot be installed (`AlwaysFail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: epoll
===> Found: epoll:ver<0.2> [via Zef::Repository::Ecosystems<cpan>]
===> Fetching [OK]: epoll:ver<0.2> to /home/alex/Blin/data/zef-data/tmp/1549582494.2026.7922/epoll-0.2.tar.gz
===> Extraction [OK]: epoll to /home/alex/Blin/data/zef-data/store/epoll-0.2.tar.gz
===> Testing: epoll:ver<0.2>
t/00-meta.t ...... ok
# Failed test 'No events'
# at t/01-simple.t line 36
# expected: ''
#      got: 'epoll-event<140219946315344>'
# Looks like you failed 1 test of 6
t/01-simple.t .... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/6 subtests 
t/02-multiple.t .. ok

Test Summary Report
-------------------
t/01-simple.t  (Wstat: 256 Tests: 6 Failed: 1)
  Failed test:  6
  Non-zero exit status: 1
Files=3, Tests=17,  9 wallclock secs ( 0.04 usr  0.00 sys +  7.07 cusr  0.36 csys =  7.47 CPU)
Result: FAIL
===> Testing [FAIL]: epoll:ver<0.2>
Failed to get passing tests, but continuing with --force-test
===> Installing: epoll:ver<0.2>
===> Install [OK] for epoll:ver<0.2>

````````````````````````````````````````````````````````

Ping @CurtTilmes

**Comment by JJ** [comment]
Maybe it's a Flapper? Again, works for me...

**Comment by AlexDaniel** [comment]
Yeah, it is. I reported it here but it is ignored: https://github.com/CurtTilmes/perl6-epoll/issues/2#issuecomment-461911699

**Comment by CurtTilmes** [comment]
Never mind.  The previous report was for a different test.  I'll mark even the simple test as extended so it won't get run during install.  It isn't a problem with the module, just the test -- it is trying to set up multiple threads to communicate within a single process.   It works fine monitoring external processes -- just need a more complicated test scheme.

**Comment by CurtTilmes** [comment]
This is a different issue from the old one (https://github.com/CurtTilmes/perl6-epoll/issues/2 t/02-multiple.t is flapping).  That test was more complicated, and could occasionally fail.  After the last report I marked that test as extended, and indeed it didn't fail this time.  The previous report was not ignored.

This report is that even the `01-simple.t` is failing?  I've never seen that fail before in any runs.  It starts up a single process, sends a single string, sees the event, does a `slurp(:close)` to make sure there are no more events coming on the process, then verifies that there are no events reported.  If it is reporting the process as readable after the `slurp(:close)` something is really wrong, not just a bad test.  It is difficult for me to debug because it always does the right thing on my host and on travis.  I'll have to get more details on the system, os, rakudo, etc. to try to replicate.

**Comment by AlexDaniel** [comment]
@CurtTilmes it's a 24 core google compute instance running with 100% CPU utilization.
